ServerEvents.recipes(event => {
    event.remove({ id: 'stellaris:misc/raw_uranium_block' })
    event.remove({ id: 'stellaris:misc/uranium_block' })
    event.remove({ id: 'mekanismadditions:walkie_talkie' })
    event.remove({ id: 'extendedae:fishbig' })
    event.remove({ id: 'extendedae:cutter/fishbig_destroy' })
    event.remove({ id: 'stellaris:misc/steel_pickaxe' })
    event.remove({ id: 'stellaris:misc/steel_axe' })
    event.remove({ id: 'stellaris:misc/steel_hoe' })
    event.remove({ id: 'stellaris:misc/steel_shovel' })
    event.remove({ id: 'stellaris:misc/steel_sword' })
})