StartupEvents.registry('block', event => {
	event.create('antimatter_block')
	.displayName('Antimatter Block')
	.soundType('amethyst')
	.hardness(10)
	.resistance(15)
	.tagBlock('minecraft:mineable/pickaxe')
	.tagBlock('minecraft:needs_iron_tool')
	.fullBlock(true)
	.requiresTool(true)

	event.create('reinforced_coal_ore')
	.displayName('Reinforced Coal Ore')
	.soundType('deepslate')
	.hardness(50)
	.resistance(50)
	.tagBlock('minecraft:mineable/pickaxe')
	.tagBlock('minecraft:needs_iron_tool')
	.fullBlock(true)
	.requiresTool(true)
	.texture('minecraft:block/deepslate_coal_ore')

	event.create('reinforced_iron_ore')
	.displayName('Reinforced Iron Ore')
	.soundType('deepslate')
	.hardness(50)
	.resistance(50)
	.tagBlock('minecraft:mineable/pickaxe')
	.tagBlock('minecraft:needs_iron_tool')
	.fullBlock(true)
	.requiresTool(true)
	.texture('minecraft:block/deepslate_iron_ore')

	event.create('reinforced_copper_ore')
	.displayName('Reinforced Copper Ore')
	.soundType('deepslate')
	.hardness(50)
	.resistance(50)
	.tagBlock('minecraft:mineable/pickaxe')
	.tagBlock('minecraft:needs_iron_tool')
	.fullBlock(true)
	.requiresTool(true)
	.texture('minecraft:block/deepslate_copper_ore')

	event.create('reinforced_gold_ore')
	.displayName('Reinforced Gold Ore')
	.soundType('deepslate')
	.hardness(50)
	.resistance(50)
	.tagBlock('minecraft:mineable/pickaxe')
	.tagBlock('minecraft:needs_iron_tool')
	.fullBlock(true)
	.requiresTool(true)
	.texture('minecraft:block/deepslate_gold_ore')

	event.create('reinforced_redstone_ore')
	.displayName('Reinforced Redstone Ore')
	.soundType('deepslate')
	.hardness(50)
	.resistance(50)
	.tagBlock('minecraft:mineable/pickaxe')
	.tagBlock('minecraft:needs_iron_tool')
	.fullBlock(true)
	.requiresTool(true)
	.texture('minecraft:block/deepslate_redstone_ore')

	event.create('reinforced_emerald_ore')
	.displayName('Reinforced Emerald Ore')
	.soundType('deepslate')
	.hardness(50)
	.resistance(50)
	.tagBlock('minecraft:mineable/pickaxe')
	.tagBlock('minecraft:needs_iron_tool')
	.fullBlock(true)
	.requiresTool(true)
	.texture('minecraft:block/deepslate_emerald_ore')

	event.create('reinforced_lapis_ore')
	.displayName('Reinforced Lapis Lazuli Ore')
	.soundType('deepslate')
	.hardness(50)
	.resistance(50)
	.tagBlock('minecraft:mineable/pickaxe')
	.tagBlock('minecraft:needs_iron_tool')
	.fullBlock(true)
	.requiresTool(true)
	.texture('minecraft:block/deepslate_lapis_ore')

	event.create('reinforced_diamond_ore')
	.displayName('Reinforced Diamond Ore')
	.soundType('deepslate')
	.hardness(50)
	.resistance(50)
	.tagBlock('minecraft:mineable/pickaxe')
	.tagBlock('minecraft:needs_iron_tool')
	.fullBlock(true)
	.requiresTool(true)
	.texture('minecraft:block/deepslate_diamond_ore')

	event.create('reinforced_quartz_ore')
	.displayName('Reinforced Nether Quartz Ore')
	.soundType('deepslate')
	.hardness(50)
	.resistance(50)
	.tagBlock('minecraft:mineable/pickaxe')
	.tagBlock('minecraft:needs_iron_tool')
	.fullBlock(true)
	.requiresTool(true)
	.texture('minecraft:block/nether_quartz_ore')

	event.create('reinforced_ancient_debris')
	.displayName('Reinforced Ancient Debris')
	.soundType('deepslate')
	.hardness(50)
	.resistance(50)
	.tagBlock('minecraft:mineable/pickaxe')
	.tagBlock('minecraft:needs_iron_tool')
	.fullBlock(true)
	.requiresTool(true)
	.texture('minecraft:block/ancient_debris_top')

	event.create('reinforced_tin_ore')
	.displayName('Reinforced Tin Ore')
	.soundType('deepslate')
	.hardness(50)
	.resistance(50)
	.tagBlock('minecraft:mineable/pickaxe')
	.tagBlock('minecraft:needs_iron_tool')
	.fullBlock(true)
	.requiresTool(true)
	.texture('mekanism:block/deepslate_tin_ore')

	event.create('reinforced_osmium_ore')
	.displayName('Reinforced Osmium Ore')
	.soundType('deepslate')
	.hardness(50)
	.resistance(50)
	.tagBlock('minecraft:mineable/pickaxe')
	.tagBlock('minecraft:needs_iron_tool')
	.fullBlock(true)
	.requiresTool(true)
	.texture('mekanism:block/deepslate_osmium_ore')

	event.create('reinforced_uranium_ore')
	.displayName('Reinforced Uranium Ore')
	.soundType('deepslate')
	.hardness(50)
	.resistance(50)
	.tagBlock('minecraft:mineable/pickaxe')
	.tagBlock('minecraft:needs_iron_tool')
	.fullBlock(true)
	.requiresTool(true)
	.texture('mekanism:block/deepslate_uranium_ore')

	event.create('reinforced_fluorite_ore')
	.displayName('Reinforced Fluorite Ore')
	.soundType('deepslate')
	.hardness(50)
	.resistance(50)
	.tagBlock('minecraft:mineable/pickaxe')
	.tagBlock('minecraft:needs_iron_tool')
	.fullBlock(true)
	.requiresTool(true)
	.texture('mekanism:block/deepslate_fluorite_ore')

	event.create('reinforced_lead_ore')
	.displayName('Reinforced Lead Ore')
	.soundType('deepslate')
	.hardness(50)
	.resistance(50)
	.tagBlock('minecraft:mineable/pickaxe')
	.tagBlock('minecraft:needs_iron_tool')
	.fullBlock(true)
	.requiresTool(true)
	.texture('mekanism:block/deepslate_lead_ore')

})